apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debezium-gke
  labels:
    name: debezium
  namespace: debezium
spec:
  replicas: 1
  serviceName: debezium
  selector:
    matchLabels:
      name: debezium
  template:
    metadata:
      labels:
        name: debezium
        version: v1
    spec:
      containers:
        - name: debezium
          image: debezium/server:1.7.0.Final
          volumeMounts:
            - name: debezium-config-volume
              mountPath: /debezium/conf
            - name: debezium-data-volume
              mountPath: /debezium/data
      volumes:
        - name: debezium-config-volume
          configMap:
            name: debezium
  volumeClaimTemplates:
    - metadata:
        name: debezium-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi